### ISSUE TITLE
Missing Plugin for affordable Sen.se ThermoPeanut

### ISSUE THREAD

**Issue by DJay-X** [luc-ass/homebridge-sense#10]
Recently I discovered the very affordable [Sen.se Peanut](https://sen.se/store/c/peanuts/) series and I bought two [ThermoPeanut](https://sen.se/store/thermopeanut/).
They are small, handy size, reliable and deliver a good overview over the collected data.
Sen.se already even offer a free [API and documentation](https://sen.se/developers/documentation/).
So this could be something very helpful to integrate as a plugin to homebridge.
Hopefully a developer will get into this and publish a plugin. Till now I was not able to already find a Plugin. Thanks in advance. 😉👍🏻

**Comment by luc-ass** [comment]
sorry, but this plugin is made for "Hello Sense" - a sleep tracker that has nothing to do with the Sen.se you are talking about. Perhaps you can start a new repo for other people that own such a device.
