### ISSUE TITLE
"Check your internet connection!" after updating Homebridge

### ISSUE THREAD

**Issue by luc-ass** [luc-ass/homebridge-sense#7]
Hey everyone,

I just updated Homebridge and now Sense tells me to check my internet connection. I double-checked my username and Password but both seem to be correct... Any ideas?

**Comment by luc-ass** [comment]
It gives me back a token so login should be fine.

**Comment by lnlyssg** [comment]
I have the same issue here, looking at the "Please check your Internet-connection" error I am getting it looks like it's returning the token which would imply the issue relates to line 136 down in sense.js

I have run a manual GET using the returned token from the error message and that returns valid data when I try it but I'm afraid I can't really figure out much more than that :(

**Comment by luc-ass** [comment]
Has been solved by @renekopcem . Thanks again! Works perfectly.
