### ISSUE TITLE
automatic intervall request

### ISSUE THREAD

**Issue by Luftloch80** [luc-ass/homebridge-sense#9]
Hi
Is it possible to add a interval timer so that the values are updated every 5minutes automatically?
With polling 
I could Control my Fan than to switch on and of At special values

Thx

**Comment by luc-ass** [comment]
Actually I would love to see this implemented! Just can't free up some time to do it. You are always welcome to help out by fiddling around and make a pull request.

**Comment by kcharwood** [comment]
Submitted a PR with this feature: #11
